DROP DATABASE IF EXISTS HOSTAL;
CREATE DATABASE HOSTAL;

USE HOSTAL;

	DROP TABLE IF EXISTS CLIENTE	;
CREATE TABLE CLIENTE(
	IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CLI VARCHAR (60),
    APELLIDO_CLI VARCHAR (60),
    TELEFONO_CLI INT,
    CORREO_CLI VARCHAR (80),
    TIPOHABITACION VARCHAR (60),
    N°OCUPANTES INT 
    /*FECHA_CLI date*/
    
);


DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
	ID_USU INT AUTO_INCREMENT PRIMARY KEY,
    NOM_USU VARCHAR (60),
    APELL_USU VARCHAR (60)
);

SELECT * FROM USUARIOS;

DROP PROCEDURE IF EXISTS SP_REG_ACT_USU;
DELIMITER $$
CREATE PROCEDURE SP_REG_ACT_USU	
(COD INT, NOM VARCHAR(60),APELL VARCHAR (60),T CHAR(1))
BEGIN
	IF T='G' THEN
		INSERT INTO USUARIOS VALUES(NULL,NOM,APELL);
	ELSEIF T='A' THEN
		UPDATE USUARIOS SET NOM_USU=NOM ,APELL_USU=APELL WHERE ID_USU=COD;
    END IF;
END $$
DELIMITER $$;

CALL SP_REG_ACT_USU(NULL,'THE BLACK HACKER','XXX','G');
CALL SP_BUS_DEL_USU(2,'THE BLACK HACKER','XXX','D');
SELECT * FROM USUARIOS;
DROP PROCEDURE IF EXISTS SP_BUS_DEL_USU;
DELIMITER $$
CREATE PROCEDURE SP_BUS_DEL_USU
(COD_U VARCHAR (3),NOM_U VARCHAR(80),APELL_U VARCHAR (60),T CHAR(1))
BEGIN
	IF T='B' THEN
		SELECT * FROM USUARIOS WHERE 
			ID_USU LIKE CONCAT('%',COD_U,'%') OR
            NOM_USU LIKE CONCAT('%',NOM_U,'%');
    ELSEIF T='D' THEN
		DELETE FROM USUARIOS WHERE ID_USU=COD_U;
	END IF;
END $$
DELIMITER $$;


DROP TABLE IF EXISTS HABITACIONE;
CREATE TABLE HABITACIONE (
ID_HABI INT AUTO_INCREMENT PRIMARY KEY,
TIPO_HABI VARCHAR (80),
DESCRIPCION VARCHAR (80)
);



DROP TABLE IF EXISTS REGISTROS1;
CREATE TABLE REGISTROS1(
ID_RE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_RE VARCHAR (80),
APELLIDO_RE VARCHAR (80),
CORREO VARCHAR (80)
);


INSERT INTO REGISTROS1 VALUES(NULL,'MARICARMAEN','ESCALANTE','MARI@hotmail.com');

SELECT * FROM REGISTROS1;




